### ISSUE TITLE
第二轮预测在哪

### ISSUE THREAD

**Issue by possessjing** [y31ling/-algorithm-to-predict-each-team-s-qualified-probabilty-for-2024-cs2-copenhagen-major#1]
https://github.com/y31ling/-algorithm-to-predict-each-team-s-qualified-probabilty-for-2024-cs2-copenhagen-major/blob/8f459e895acc467e596470727e2c8e9818623417/main.py#L70-L71
请问这里为什么是从第3轮到第5轮，第二轮去哪了

**Comment by y31ling** [comment]
第三轮开始是瑞士轮，第二轮是在前一轮胜负基础上根据种子顺序进行对阵，在 57行开始
 # Function to decide the next round's matches based on winners and selection rules
这后面

**Comment by possessjing** [comment]
每执行一次simulate_match是进行一轮比赛，q=0时执行了第一轮，while q < 3时执行了2,3,4轮，总共不是5轮比赛吗

**Comment by possessjing** [comment]
57行后面不是decide_next_round_matches的定义吗，没看到第二轮比赛执行的代码啊，整个流程总共就执行了4次simulate_match，是不是最新代码没push

**Comment by y31ling** [comment]
代码已更新，感谢指正
